type: vertical-stack
cards:
  - type: custom:mushroom-title-card
    title: Waste collection
  - type: custom:auto-entities
    card:
      type: entities
    entities:
      - entity: sensor.plast
      - entity: sensor.pap
      - entity: sensor.restaffald
    sort:
      method: attribute
      attribute: days_left
      numeric: true
